<h1>2D Numpy</h1>

In [2]:
import numpy as np

In [10]:
a = [[11,12,13],[21,22,23],[31,32,33]]
A = np.array(a)
print(A)
print(A.ndim)
print(A.shape)
print(A.size)

# Accessing using index
print(A[0,0]) # [row, column]
print(A[1,2]) # [row, column]

[[11 12 13]
 [21 22 23]
 [31 32 33]]
2
(3, 3)
9
11
23


<h3>Slicing</h3>

In [11]:
# Slicing
B = A[0:2,1:3] # [row_start:row_end, column_start:column_end]
print(B)

[[12 13]
 [22 23]]


<h3>Adding 2D arrays</h3>

In [13]:
X = np.array([[1,0],[0,1]])
Y = np.array([[2,1],[1,2]])
Z = np.add(X,Y)
print(Z)

[[3 1]
 [1 3]]


<h3>Multiplying 2D arrays</h3>

In [18]:
X = np.array([[1,0],[0,1]])
Y = np.array([[2,1],[1,2]])

Z = 2 * Y
print(Z)

Z = np.dot(X,Y)
print(Z)

[[4 2]
 [2 4]]
[[2 1]
 [1 2]]
